<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251213141125 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shipping_providers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, display_name VARCHAR(150) NOT NULL, base_endpoint VARCHAR(255) DEFAULT NULL, request_schema JSON DEFAULT NULL, response_schema JSON DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4D085205E237E06 ON shipping_providers (name)');
        $this->addSql('CREATE TABLE shipping_services (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, display_name VARCHAR(100) NOT NULL, base_price NUMERIC(10, 2) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, shipping_provider_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EFDDAFC686382F09 ON shipping_services (shipping_provider_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_provider_code ON shipping_services (shipping_provider_id, code)');
        $this->addSql('CREATE TABLE user_global_pricing_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, percentage_markup NUMERIC(5, 4) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9FDE793A76ED395 ON user_global_pricing_rules (user_id)');
        $this->addSql('CREATE TABLE user_provider_pricing_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, percentage_markup NUMERIC(5, 4) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, user_id INT NOT NULL, shipping_provider_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A796F0F6A76ED395 ON user_provider_pricing_rules (user_id)');
        $this->addSql('CREATE INDEX IDX_A796F0F686382F09 ON user_provider_pricing_rules (shipping_provider_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_provider ON user_provider_pricing_rules (user_id, shipping_provider_id)');
        $this->addSql('CREATE TABLE user_service_pricing_overrides (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fixed_price NUMERIC(10, 2) DEFAULT NULL, percentage_markup NUMERIC(5, 4) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, user_id INT NOT NULL, shipping_service_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3C0051DA76ED395 ON user_service_pricing_overrides (user_id)');
        $this->addSql('CREATE INDEX IDX_3C0051D55A7F9B8 ON user_service_pricing_overrides (shipping_service_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_service ON user_service_pricing_overrides (user_id, shipping_service_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, clerk_user_id VARCHAR(191) NOT NULL, email VARCHAR(191) DEFAULT NULL, name VARCHAR(150) NOT NULL, last_name VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E92A184CBC ON users (clerk_user_id)');
        $this->addSql('ALTER TABLE shipping_services ADD CONSTRAINT FK_EFDDAFC686382F09 FOREIGN KEY (shipping_provider_id) REFERENCES shipping_providers (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_global_pricing_rules ADD CONSTRAINT FK_9FDE793A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_provider_pricing_rules ADD CONSTRAINT FK_A796F0F6A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_provider_pricing_rules ADD CONSTRAINT FK_A796F0F686382F09 FOREIGN KEY (shipping_provider_id) REFERENCES shipping_providers (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_service_pricing_overrides ADD CONSTRAINT FK_3C0051DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_service_pricing_overrides ADD CONSTRAINT FK_3C0051D55A7F9B8 FOREIGN KEY (shipping_service_id) REFERENCES shipping_services (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shipping_services DROP CONSTRAINT FK_EFDDAFC686382F09');
        $this->addSql('ALTER TABLE user_global_pricing_rules DROP CONSTRAINT FK_9FDE793A76ED395');
        $this->addSql('ALTER TABLE user_provider_pricing_rules DROP CONSTRAINT FK_A796F0F6A76ED395');
        $this->addSql('ALTER TABLE user_provider_pricing_rules DROP CONSTRAINT FK_A796F0F686382F09');
        $this->addSql('ALTER TABLE user_service_pricing_overrides DROP CONSTRAINT FK_3C0051DA76ED395');
        $this->addSql('ALTER TABLE user_service_pricing_overrides DROP CONSTRAINT FK_3C0051D55A7F9B8');
        $this->addSql('DROP TABLE shipping_providers');
        $this->addSql('DROP TABLE shipping_services');
        $this->addSql('DROP TABLE user_global_pricing_rules');
        $this->addSql('DROP TABLE user_provider_pricing_rules');
        $this->addSql('DROP TABLE user_service_pricing_overrides');
        $this->addSql('DROP TABLE users');
    }
}
