<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251213174339 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Refactor schema: rename tables and update relationships';
    }

    public function up(Schema $schema): void
    {
        // 1. Primero eliminamos la FK problemática de shipping_services
        $this->addSql('ALTER TABLE shipping_services DROP CONSTRAINT IF EXISTS fk_efddafc686382f09');

        // 2. Eliminamos las constraints de las tablas viejas
        $this->addSql('ALTER TABLE user_global_pricing_rules DROP CONSTRAINT IF EXISTS fk_9fde793a76ed395');
        $this->addSql('ALTER TABLE user_provider_pricing_rules DROP CONSTRAINT IF EXISTS fk_a796f0f6a76ed395');
        $this->addSql('ALTER TABLE user_provider_pricing_rules DROP CONSTRAINT IF EXISTS fk_a796f0f686382f09');
        $this->addSql('ALTER TABLE user_service_pricing_overrides DROP CONSTRAINT IF EXISTS fk_3c0051da76ed395');
        $this->addSql('ALTER TABLE user_service_pricing_overrides DROP CONSTRAINT IF EXISTS fk_3c0051d55a7f9b8');

        // 3. Ahora sí podemos eliminar las tablas viejas
        $this->addSql('DROP TABLE IF EXISTS user_service_pricing_overrides');
        $this->addSql('DROP TABLE IF EXISTS user_provider_pricing_rules');
        $this->addSql('DROP TABLE IF EXISTS user_global_pricing_rules');
        $this->addSql('DROP TABLE IF EXISTS shipping_services');
        $this->addSql('DROP TABLE IF EXISTS shipping_providers');
        $this->addSql('DROP TABLE IF EXISTS users');

        // 4. Creamos las nuevas tablas
        $this->addSql('CREATE TABLE shipping_provider (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, endpoint_url VARCHAR(500) NOT NULL, request_config JSON NOT NULL, response_config JSON NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, clerk_user_id VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6492A184CBC ON "user" (clerk_user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');

        $this->addSql('CREATE TABLE user_global_pricing_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, markup_percentage DOUBLE PRECISION DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_44C1C859A76ED395 ON user_global_pricing_rule (user_id)');

        $this->addSql('CREATE TABLE user_provider_pricing_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, markup_percentage DOUBLE PRECISION DEFAULT NULL, user_id INT NOT NULL, shipping_provider_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FEBCE7B1A76ED395 ON user_provider_pricing_rule (user_id)');
        $this->addSql('CREATE INDEX IDX_FEBCE7B186382F09 ON user_provider_pricing_rule (shipping_provider_id)');

        $this->addSql('CREATE TABLE user_service_pricing_override (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_code VARCHAR(255) NOT NULL, fixed_price DOUBLE PRECISION DEFAULT NULL, markup_percentage DOUBLE PRECISION DEFAULT NULL, user_id INT NOT NULL, shipping_provider_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_798D61D7A76ED395 ON user_service_pricing_override (user_id)');
        $this->addSql('CREATE INDEX IDX_798D61D786382F09 ON user_service_pricing_override (shipping_provider_id)');

        // 5. Agregamos las FKs de las nuevas tablas
        $this->addSql('ALTER TABLE user_global_pricing_rule ADD CONSTRAINT FK_44C1C859A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_provider_pricing_rule ADD CONSTRAINT FK_FEBCE7B1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_provider_pricing_rule ADD CONSTRAINT FK_FEBCE7B186382F09 FOREIGN KEY (shipping_provider_id) REFERENCES shipping_provider (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_service_pricing_override ADD CONSTRAINT FK_798D61D7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_service_pricing_override ADD CONSTRAINT FK_798D61D786382F09 FOREIGN KEY (shipping_provider_id) REFERENCES shipping_provider (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // Revertir: eliminar nuevas tablas y recrear las viejas
        $this->addSql('ALTER TABLE user_global_pricing_rule DROP CONSTRAINT FK_44C1C859A76ED395');
        $this->addSql('ALTER TABLE user_provider_pricing_rule DROP CONSTRAINT FK_FEBCE7B1A76ED395');
        $this->addSql('ALTER TABLE user_provider_pricing_rule DROP CONSTRAINT FK_FEBCE7B186382F09');
        $this->addSql('ALTER TABLE user_service_pricing_override DROP CONSTRAINT FK_798D61D7A76ED395');
        $this->addSql('ALTER TABLE user_service_pricing_override DROP CONSTRAINT FK_798D61D786382F09');

        $this->addSql('DROP TABLE shipping_provider');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_global_pricing_rule');
        $this->addSql('DROP TABLE user_provider_pricing_rule');
        $this->addSql('DROP TABLE user_service_pricing_override');

        // Recrear tablas viejas
        $this->addSql('CREATE TABLE shipping_providers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, display_name VARCHAR(150) NOT NULL, base_endpoint VARCHAR(255) DEFAULT NULL, request_schema JSON DEFAULT NULL, response_schema JSON DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_a4d085205e237e06 ON shipping_providers (name)');

        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, clerk_user_id VARCHAR(191) NOT NULL, email VARCHAR(191) DEFAULT NULL, name VARCHAR(150) NOT NULL, last_name VARCHAR(150) NOT NULL, roles JSON DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_1483a5e92a184cbc ON users (clerk_user_id)');

        $this->addSql('CREATE TABLE user_global_pricing_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, percentage_markup NUMERIC(5, 4) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_9fde793a76ed395 ON user_global_pricing_rules (user_id)');

        $this->addSql('CREATE TABLE user_provider_pricing_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, percentage_markup NUMERIC(5, 4) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, user_id INT NOT NULL, shipping_provider_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_a796f0f6a76ed395 ON user_provider_pricing_rules (user_id)');
        $this->addSql('CREATE INDEX idx_a796f0f686382f09 ON user_provider_pricing_rules (shipping_provider_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_provider ON user_provider_pricing_rules (user_id, shipping_provider_id)');

        $this->addSql('CREATE TABLE user_service_pricing_overrides (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fixed_price NUMERIC(10, 2) DEFAULT NULL, percentage_markup NUMERIC(5, 4) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, user_id INT NOT NULL, shipping_service_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_3c0051da76ed395 ON user_service_pricing_overrides (user_id)');
        $this->addSql('CREATE INDEX idx_3c0051d55a7f9b8 ON user_service_pricing_overrides (shipping_service_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_service ON user_service_pricing_overrides (user_id, shipping_service_id)');

        $this->addSql('CREATE TABLE shipping_services (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, shipping_provider_id INT NOT NULL, PRIMARY KEY (id))');

        $this->addSql('ALTER TABLE user_global_pricing_rules ADD CONSTRAINT fk_9fde793a76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_provider_pricing_rules ADD CONSTRAINT fk_a796f0f6a76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_provider_pricing_rules ADD CONSTRAINT fk_a796f0f686382f09 FOREIGN KEY (shipping_provider_id) REFERENCES shipping_providers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_service_pricing_overrides ADD CONSTRAINT fk_3c0051da76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_service_pricing_overrides ADD CONSTRAINT fk_3c0051d55a7f9b8 FOREIGN KEY (shipping_service_id) REFERENCES shipping_services (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shipping_services ADD CONSTRAINT fk_efddafc686382f09 FOREIGN KEY (shipping_provider_id) REFERENCES shipping_providers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
